# Generated by Django 4.1.1 on 2022-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_course_max_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_student',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_student',
            field=models.IntegerField(default=100),
        ),
    ]
