# Generated by Django 4.1.1 on 2022-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_course_course_code_course_course_semeter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='describetion',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
