# Generated by Django 4.1.1 on 2022-09-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
